DELIMITER $$

DROP PROCEDURE IF EXISTS DeployIndex$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `DeployIndex`(IN TBL_SCHEMA VARCHAR(16), IN TBL_NAME VARCHAR(32), IN IDX_NAME VARCHAR(64), IN IDX_TEXT VARCHAR(2048))
BEGIN

SELECT COUNT(1)
INTO @INDEX_EXISTS
FROM information_schema.statistics
WHERE table_schema = TBL_SCHEMA
AND table_name = TBL_NAME
AND index_name = IDX_NAME;

SET @IDX_TXT = IDX_TEXT;
IF @INDEX_EXISTS = 0 THEN
	PREPARE STMT FROM @IDX_TXT;
	EXECUTE STMT;
END IF;

END$$

DELIMITER ;
