DELIMITER $$

DROP PROCEDURE IF EXISTS FindColumn$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `FindColumn`(IN columnRegex VARCHAR(250))
BEGIN

SELECT DISTINCT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME
FROM information_schema.columns
WHERE COLUMN_NAME RLIKE columnRegex
ORDER BY TABLE_SCHEMA ASC, TABLE_NAME ASC, COLUMN_NAME ASC;

END$$

DELIMITER ;
# CALL FindColumn('placementGroup');
