alias la="ls -a"                                                                                                                                                                                                                          
alias lsa="ls -al"

