-- drop table HetQueueTool;

create table HetQueueTool (
	ID INT IDENTITY(1, 1),
	PROCESSBATCH_ID NUMERIC(19, 0) NOT NULL,
	HetQueueNumber INT NOT NULL,
	TOOL_ID NUMERIC(19, 0) NOT NULL,
	PRIMARY KEY CLUSTERED (ID)
);


ALTER TABLE HetQueueTool WITH CHECK ADD CONSTRAINT FK_HETQTOOL_ID FOREIGN KEY (TOOL_ID) REFERENCES TOOL (ID);
ALTER TABLE HetQueueTool WITH CHECK ADD CONSTRAINT FK_HETQTOOL_PROCESSBATCH_ID FOREIGN KEY (PROCESSBATCH_ID) REFERENCES PROCESSBATCH (ID);


