-- drop table ResultsGSF;

create table ResultsGSF (
	ID INT IDENTITY(1, 1),
	PROCESSBATCH_ID NUMERIC(19, 0) NOT NULL,
	PRODUCT_ID NUMERIC(19, 0) NOT NULL,
	STEP_ID NUMERIC(19, 0) NOT NULL,
	ForecastDateTime DATETIME NOT NULL,
	ForecastId INT NOT NULL,
	ShiftId INT NOT NULL,
	n_FcWafWIP INT,
	n_FcPotWafWIP INT,
	n_TargWafWIP INT,
	n_LoTargWafWIP INT,
	n_UpTargWafWIP INT,
	PRIMARY KEY CLUSTERED (ID)
);


ALTER TABLE ResultsGSF WITH CHECK ADD CONSTRAINT FK_RESULTSGSF_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID);
ALTER TABLE ResultsGSF WITH CHECK ADD CONSTRAINT FK_RESULTSGSF_STEP_ID FOREIGN KEY (STEP_ID) REFERENCES STEP (ID);
ALTER TABLE ResultsGSF WITH CHECK ADD CONSTRAINT FK_RESULTSGSF_PROCESSBATCH_ID FOREIGN KEY (PROCESSBATCH_ID) REFERENCES PROCESSBATCH (ID);

-- select * from im9..ResultsGSF
