-- drop table ResultsQ;

create table ResultsQ (
	ID INT IDENTITY(1, 1),
	PROCESSBATCH_ID NUMERIC(19, 0) NOT NULL,
	HetQueueNumber INT NOT NULL,
	f_Load FLOAT,
	f_Mix FLOAT,
	f_LxM FLOAT,
	PRIMARY KEY CLUSTERED (ID)
);

ALTER TABLE ResultsQ WITH CHECK ADD CONSTRAINT FK_RESULTSQ_PROCESSBATCH_ID FOREIGN KEY (PROCESSBATCH_ID) REFERENCES PROCESSBATCH (ID);

-- select * from im..ResultsQ
