-- drop table ResultsTZ;

create table ResultsTZ (
	ID NUMERIC(19, 0) IDENTITY(1, 1),
	PROCESSBATCH_ID NUMERIC(19, 0) NOT NULL,
	TOOL_ID NUMERIC(19, 0) NOT NULL,
	TOOLSTATE_ID NUMERIC(19, 0) NOT NULL,
	f_InState FLOAT,
	t_InStateAve NUMERIC(19, 0),
	PRIMARY KEY CLUSTERED (ID)
);


ALTER TABLE RESULTSTZ WITH CHECK ADD CONSTRAINT FK_RESULTSTZ_TOOL_ID FOREIGN KEY (TOOL_ID) REFERENCES TOOL (ID);
ALTER TABLE RESULTSTZ WITH CHECK ADD CONSTRAINT FK_RESULTSTZ_TOOLSTATE_ID FOREIGN KEY (TOOLSTATE_ID) REFERENCES TOOLSTATE (ID);
ALTER TABLE RESULTSTZ WITH CHECK ADD CONSTRAINT FK_RESULTSTZ_PROCESSBATCH_ID FOREIGN KEY (PROCESSBATCH_ID) REFERENCES PROCESSBATCH (ID);

-- select * from im..ResultsTZ
